### ISSUE TITLE
missing express dependency

### ISSUE THREAD

**Issue by barabo** [cerner/cds-services-tutorial#11]
Going through the tutorial in OSX for the first time I saw this:
```
msft-mbp:cds-services-tutorial can$ npm run start-server

> cds-services-tutorial@1.0.0 start-server /Users/can/code/cds-services-tutorial
> nodemon ./index.js localhost 3000

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./index.js localhost 3000`
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- /Users/can/code/cds-services-tutorial/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/can/code/cds-services-tutorial/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/can/code/cds-services-tutorial/index.js' ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

I'm assuming there's a missing dependency somewhere - or maybe the instructions should include extra `npm install express` instructions.  I'm happy to send a PR - just let me know how to address it.

FWIW: I'm using OSX with the latest `node` and `npm` versions (installed with `homebrew`).

**Comment by barabo** [comment]
Actually, I think I solved my own problem.  I forgot to run `npm install` before starting the server.  My bad!
